// Build step: regenerate styles.min.css / script.min.js from the readable sources.
//
//   npm install     (once)
//   npm run build   (after every edit to styles.css or script.js)
//
// Always edit styles.css / script.js - the .min files are generated output and
// any change made directly to them is lost on the next build.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import CleanCSS from 'clean-css';
import { minify } from 'terser';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

function report(label, from, to) {
    const saved = (100 - (to / from) * 100).toFixed(1);
    const kb = (n) => (n / 1024).toFixed(1) + ' KB';
    console.log(`${label.padEnd(16)} ${kb(from).padStart(9)} -> ${kb(to).padStart(9)}  (-${saved}%)`);
}

// ---- CSS ------------------------------------------------------------------
const cssSource = readFileSync(join(root, 'styles.css'), 'utf8');
// Level 1 only: whitespace, comments, colour/unit shortening. Level 2 would
// reorder and merge selectors across the file for another ~1 KB, which is not
// worth the risk of shifting cascade order in a hand-written stylesheet.
const css = new CleanCSS({ level: 1, returnPromise: false }).minify(cssSource);

if (css.errors.length) {
    console.error('CSS errors:', css.errors);
    process.exit(1);
}
if (css.warnings.length) {
    console.warn('CSS warnings:', css.warnings);
}

const banner = '/* Generated by "npm run build" - edit styles.css / script.js instead. */\n';

writeFileSync(join(root, 'styles.min.css'), banner + css.styles + '\n');
report('styles.css', Buffer.byteLength(cssSource), Buffer.byteLength(css.styles));

// ---- JS -------------------------------------------------------------------
const jsSource = readFileSync(join(root, 'script.js'), 'utf8');
const js = await minify(jsSource, {
    compress: { passes: 2 },
    mangle: true,
    format: { comments: false },
});

writeFileSync(join(root, 'script.min.js'), banner + js.code + '\n');
report('script.js', Buffer.byteLength(jsSource), Buffer.byteLength(js.code));
